# Basic configuration for setting up the 

[global]
project = "twoDValidations"
project_name = "ICARUS BNB MC" # toadd
file = "/Users/msotgia/dev_areas/twoDValidationsStudies/trackValidations/writerTwoDValidationsRedoCorrectBestmatch.root"
# file = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/trackValidations/writerTwoDValidations.root"
# outdir = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/trackValidations/plotStuff/samplePlots/configurationSingles1D/"
outdir = "/Users/msotgia/dev_areas/twoDValidationsStudies/trackValidations/makePlots/configurationSingles1D/Slices/"
fontsize = 13
labelfontsize = 28

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[analysis_Slices]
merge_on = "Evt"
# density = true
# figsize = [5.0, 3.5]

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[[analysis_Slices.dataset]]
name = "GeneralSlice/DconfigD/configD"
# No `style` entr --> default to black line 2 pt
label = "2D + DNNROI\nw/ Pulse Trains = 10"
style = "style_dnnpt"

[[analysis_Slices.dataset]]
name = "GeneralSlice/DconfigC/configC"
# No `style` entr --> default to black line 2 pt
label = "2D + DNNROI\nw/o Pulse Trains"
style = "style_dnn"

[[analysis_Slices.dataset]]
name = "GeneralSlice/DconfigB/configB"
style = "style_2d"
label = "2D signal proc."

[[analysis_Slices.dataset]]
name = "GeneralSlice/DconfigA/configA"
# No `style` entr --> default to black line 2 pt
label = "1D signal proc."

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

[[analysis_Slices.plot]]
label = "# PFP / Slice"
product = "nPfpsPerSlice"
# yscale = "log"
# showmedian = ".1%"
ylabel = "Slices [#]"
binning = {bins = 14, limits = [0.5, 14.5], flow = "sum", integer = true}

[[analysis_Slices.plot]]
label = "$\\Delta_\\mathrm{reco, true}$ vertex position"
product = "trueRecoDiffVertex3d"
yscale = "log"
# ylabel = "PFPs [#]"
ylabel = "Slices [#]"
binning = {bins = 40, limits = [0, 350], flow = "sum", unit = "cm"}

[[analysis_Slices.plot]]
label = "# Slices / Spill"
filter = {name = "max_slice_count", event_column = "Evt", slice_column = "Slice", product = "sliceCount"}
product = "sliceCount"
yscale = "log"
# ylabel = "PFPs [#]"
binning = {bins = 8, limits = [0.5, 8.5], flow = "sum", integer = true}

# --------------------------------------------------------------------
# =====================================================================
# --------------------------------------------------------------------

# Possible choices 
# ['fill', 'step', 'errorbar', 'band', 'bar', 'barstep']

# this overwrites the default style if needed
[style_default]
histtype = "errorbar"
color = "k"
linewidth = 1

[style_2d]
histtype = "step"
yerr = false
color = "tab:green"
# alpha = 0.5
linestyle = ":"
linewidth = 3

[style_dnn]
histtype = "step"
color = "tab:orange"
yerr = false
linestyle = "--"
linewidth = 5

[style_dnnpt]
histtype = "step"
color = "tab:blue"
yerr = false
linewidth = 7

